[toolchain]
anchor_version = "0.31.0"

[features]
seeds = false
skip-lint = false
resolution = true

[programs.localnet]
escrow = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
multi_presale = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
escrow = "HVpfkkSxd5aiCALZ8CETUxrWBfUwWCtJSxxtUsZhFrt4"
multi_presale = "3n4Jusc6GmZXTJapNbDpr4DYKFSsZUhz2XKuJVL6Kmy5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "target/types"