[toolchain]
anchor_version = "0.31.0"

[features]
seeds = false
skip-lint = false

[programs.mainnet]
escrow = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "deployments/soon/types"