[toolchain]
anchor_version = "0.31.0"

[features]
seeds = false
skip-lint = false

[programs.mainnet-beta]
escrow = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet-beta"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solana/**/*.ts"

[workspace]
types = "deployments/solana/types"