[toolchain]
anchor_version = "0.31.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
escrow = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.mainnet-beta]
escrow = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
# SOON network uses similar wallet structure to Solana
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/soon/**/*.ts"

[workspace]
types = "deployments/soon/types"

# SOON-specific configurations
[soon]
# SOON network RPC endpoints - CORRECTED with /rpc suffix
mainnet_rpc = "https://rpc.mainnet.soo.network/rpc"
testnet_rpc = "https://rpc.testnet.soo.network/rpc"
devnet_rpc = "https://rpc.fc.devnet.soo.network/rpc"

# Explorer
mainnet_explorer = "https://explorer.soo.network/"

# Chain compatibility: 100% Solana-compatible
chain_id = "same as Solana"
commitment = "confirmed"
timeout = 60000

# SVM compatibility: Decoupled SVM - identical to Solana
svm_version = "Decoupled SVM"
solana_compatibility = true
program_loader = "BPFLoaderUpgradeab1e11111111111111111111111"